# SPDX-License-Identifier: GPL-3.0-or-later
"""유니티 마지막 수단 — 게임이 글자를 그리는 순간 가로채 바꿔치기.

## 왜 이런 게 필요한가

지금까지의 방법은 **게임 파일을 직접 고치는** 것입니다. 대개 잘 됩니다.
그런데 유니티 게임 중에는 이런 것이 있습니다.

    파일은 분명히 고쳤는데 게임 화면은 그대로다

게임이 그 글을 **우리가 고친 자리에서 안 읽고 있는** 것입니다. 코드 안에
박혀 있거나, 게임이 스스로 만든 형식이거나, 우리가 못 읽는 곳에 있습니다.

RPG Maker · Ren'Py · 티라노는 이럴 때 **덧씌우기** 로 뚫습니다 — 게임의
제 코드에 한 줄 끼워 넣어 그리기 직전에 바꿔치는 것입니다. 그런데
유니티는 컴파일되어 있어 끼워 넣을 자리가 없습니다.

## 그래서 남의 것을 빌립니다

**BepInEx**(모드 얹는 틀)와 **XUnity.AutoTranslator**(글자 가로채는 것).
둘 다 무료이고 MIT · LGPL 이라 써도 됩니다.

## AutoTranslator 를 쓰기 싫어서 만든 도구인데?

맞습니다. 그런데 **성격이 반대가 됩니다.**

    원래 AutoTranslator   글자가 뜰 때마다 인터넷에 물어봄 → 멈칫함
    우리가 쓰는 방식       이미 만든 번역표를 먹여 둠      → 찾기만 함

인터넷 번역기는 **꺼 둡니다**(``Endpoint=`` 를 비웁니다). 물어볼 데가
없으니 멈칫할 일이 없습니다. 재료를 미리 다 준비해 두는 것이 차이입니다.

## 그래도 못 없애는 것

    · 백신 오탐 — DLL 을 밀어 넣는 방식 자체의 성질입니다
    · IL2CPP 에서 글자 일부만 잡힘 — 플러그인 쪽 한계입니다
    · 한글 경로 — 걸리는지 아닌지는 실제로 돌려 봐야 압니다

그래서 이것은 **기본이 아니라 마지막 수단**입니다. 지금 방법으로 되는
게임에까지 DLL 을 밀어 넣을 이유는 없습니다.
"""

from __future__ import annotations

import shutil
import zipfile
from dataclasses import dataclass, field
from pathlib import Path

# 이 플러그인이 번역표를 읽는 파일 이름.
TABLE = "_AutoGeneratedTranslations.txt"
# 플러그인이 **실제로 읽는** 자리. 게임 폴더 맨 위가 아닙니다 — 거기에
# 써 두면 조용히 무시되고 기본 설정으로 돕니다. 실제로 그렇게 됐습니다:
# 인터넷 번역기가 켜진 채 중국어가 영어로 바뀌었습니다.
CONFIG = "BepInEx/config/AutoTranslatorConfig.ini"
TRANSLATION = "BepInEx/Translation"
ADDED = "__gameloc_runtime__.txt"      # 우리가 넣은 것 목록 (되돌리기용)

# 받을 곳. 파일을 우리 배포본에 넣지 않고 **받아서** 씁니다 — 남의
# 프로그램을 재배포하지 않는 편이 깔끔하고, 판이 낡을 일도 없습니다.
XUNITY_RELEASES = "https://github.com/bbepis/XUnity.AutoTranslator/releases"
BEPINEX_MONO = "https://github.com/BepInEx/BepInEx/releases"
BEPINEX_IL2CPP = "https://builds.bepinex.dev/projects/bepinex_be"


def _noop(_: str) -> None:
    pass


# ---------------------------------------------------------------- 무엇이 필요한가

@dataclass
class Need:
    """이 게임에 무엇을 넣어야 하는가."""

    backend: str = ""            # "Mono" | "IL2CPP"
    bits: int = 64
    unity: str = ""
    bepinex_hint: str = ""       # 고를 파일 이름에 든 낱말
    xunity_hint: str = ""
    where: str = ""              # 받는 곳
    # 비어 있지 않으면 **우리 것으로는 못 합니다.** 그 까닭이 사람 말로.
    blocked: str = ""
    notes: list[str] = field(default_factory=list)

    def ok(self) -> bool:
        return bool(self.backend)


def _bits(root: Path) -> int:
    """실행 파일이 32비트인지 64비트인지. PE 머리를 읽습니다."""
    import struct

    for exe in sorted(root.glob("*.exe")):
        try:
            data = exe.read_bytes()[:4096]
            off = struct.unpack_from("<I", data, 0x3C)[0]
            if data[off:off + 4] != b"PE\x00\x00":
                continue
            machine = struct.unpack_from("<H", data, off + 4)[0]
            return 32 if machine == 0x014C else 64
        except Exception:                               # noqa: BLE001
            continue
    return 64


# 우리가 지고 다니는 BepInEx 5 가 **못 버티는 유니티 판**.
#
# 진짜 게임(유니티 6000.3.18f1 · Mono)에서 이렇게 죽었습니다.
#
#   System.MissingMethodException: Method not found:
#     void System.Reflection.Module.GetPEKind(...)
#     at BepInEx.Preloader.PreloaderRunner.PreloaderPreMain()
#
# BepInEx 5 가 쓰는 .NET 함수가 유니티 6000 의 새 런타임에는 없습니다.
# 시작하자마자 죽고, **실패한 주입 때문에 게임까지 검은 화면이 됩니다.**
# 되돌리기 전에는 게임을 못 켭니다.
#
# 그래서 안 되는 줄 알면 **아예 깔지 않습니다.** 깔고 나서 안 되는 것보다
# 훨씬 낫습니다 — 사용자는 무엇이 게임을 망가뜨렸는지 모릅니다.
MONO_MAX_UNITY = 6000


def unity_major(version: str) -> int:
    """``6000.3.18f1`` → ``6000``. 못 읽으면 0."""
    head = (version or "").split(".", 1)[0]
    return int(head) if head.isdigit() else 0


def mono_too_new(version: str) -> str:
    """우리 BepInEx 로는 못 다루는 판인가. 되면 빈 문자열."""
    major = unity_major(version)
    if major and major >= MONO_MAX_UNITY:
        return (f"유니티 {version} 은 우리가 지고 다니는 BepInEx 로는 "
                "덮어씌우기를 못 합니다. 게임이 켜지기 전에 죽고, 그 바람에 "
                "게임까지 안 켜집니다.")
    return ""


def plan(info) -> Need:
    """게임을 보고 무엇이 필요한지 정합니다. 아무것도 안 건드립니다."""
    need = Need(backend=info.scripting_backend, unity=info.unity_version,
                bits=_bits(Path(info.root)))
    if info.engine != "unity":
        need.notes.append("이 길은 유니티 게임에서만 씁니다.")
        need.backend = ""
        return need
    if not need.backend:
        need.notes.append(
            "이 게임이 Mono 인지 IL2CPP 인지 알아내지 못했습니다.")
        return need

    if need.backend == "IL2CPP":
        need.bepinex_hint = f"IL2CPP · win_x{need.bits}"
        need.xunity_hint = "BepInEx-IL2CPP"
        need.where = BEPINEX_IL2CPP
        need.notes.append(
            "IL2CPP 게임입니다. 플러그인 제작자가 'IL2CPP 는 글자 잡아내는 "
            "것이 시원찮다' 고 적어 두었습니다. 일부만 바뀌거나 화면을 다시 "
            "그려야 나올 수 있습니다.")
    else:
        need.bepinex_hint = f"BepInEx_win_x{need.bits}"
        need.xunity_hint = "BepInEx"
        need.where = BEPINEX_MONO
        too_new = mono_too_new(need.unity)
        if too_new:
            need.blocked = too_new
            need.notes.append(too_new)
            need.notes.append(
                "고쳐진 최신 개발판이 있습니다. "
                f"{BEPINEX_IL2CPP} 에서 이름에 [Unity.Mono] 와 "
                f"[win-x{need.bits}] 가 든 것을 받아 '받아둔 폴더' 로 "
                "넣어 주시면 그것을 씁니다.")

    need.notes.append(
        "이 방법은 게임에 DLL 을 밀어 넣습니다. 백신이 오탐할 수 있습니다. "
        "게임 파일 자체는 안 건드리므로, 넣은 것을 지우면 원래대로 됩니다.")
    return need


# ---------------------------------------------------------------- 번역표

def make_table(proj, lang: str) -> tuple[str, int, int]:
    """번역표를 플러그인이 읽는 모양(``원문=번역문``)으로 만듭니다.

    돌려주는 것: ``(글, 쓴 줄 수, 건너뛴 줄 수)``
    """
    def esc(s: str) -> str:
        return s.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\\n")

    lines: list[str] = []
    seen: set[str] = set()
    skipped = 0
    for e in proj.entries:
        ko = (e.translations.get(lang) or "").strip()
        if not ko or ko == e.text:
            continue
        # 이 파일은 한 줄에 한 쌍이고 첫 '=' 에서 갈립니다. 그래서
        # 원문에 '=' 가 있으면 엉뚱한 데서 잘립니다.
        # 또 원문에 **글자 그대로** \n 이 들어 있으면, 우리가 진짜
        # 줄바꿈을 \n 으로 적은 것과 구분할 수 없습니다. 둘 다 뺍니다 —
        # 잘못 맞느니 빠지는 편이 낫습니다.
        if "=" in e.text or "\\n" in e.text or "\\r" in e.text:
            skipped += 1
            continue
        key = esc(e.text)
        if not key.strip() or key in seen:
            continue
        seen.add(key)
        lines.append(f"{key}={esc(ko)}")
    return "\n".join(lines) + ("\n" if lines else ""), len(lines), skipped


# 글자 모양으로 무슨 말인지 알아내기. 코드 순서가 곧 우선순위입니다 —
# 가나가 하나라도 있으면 한자가 아무리 많아도 일본어입니다.
_KANA = "\u3040-\u309f\u30a0-\u30ff"
_HANGUL = "\uac00-\ud7af\u1100-\u11ff"
_HAN = "\u4e00-\u9fff\u3400-\u4dbf"
_CYRIL = "\u0400-\u04ff"

_SCRIPTS = (
    ("ja", "일본어", _KANA),
    ("ko", "한국어", _HANGUL),
    ("ru", "러시아어", _CYRIL),
    ("zh-CN", "중국어", _HAN),
    ("en", "영어", "A-Za-z"),
)

LANG_NAMES = {code: name for code, name, _r in _SCRIPTS}

# 한 말이 이 정도는 차지해야 '이 게임의 말' 이라고 할 수 있습니다.
# 게임에 따라 번역표에 여러 말이 한꺼번에 들어 있습니다 — 유니티
# Localization 을 쓰는 게임은 영어·중국어·러시아어·터키어 표를 다 갖고
# 있습니다. 그럴 때 하나를 골라 박으면 나머지가 전부 번역이 안 됩니다.
_ENOUGH = 0.60


def guess_lang(texts) -> tuple[str, str]:
    """원문이 무슨 말인지 **글자 모양으로** 알아냅니다. ``(코드, 근거)``.

    프로젝트에 원문 언어가 '자동' 으로 되어 있으면 우리는 그걸 모릅니다.
    예전에는 그럴 때 일본어로 박아 버렸습니다. 영어 게임이든 중국어
    게임이든요 — 플러그인은 원문이 그 말처럼 안 생기면 아예 손을 안 대기
    때문에, 번역표를 다 깔아 놓고도 한 줄도 안 바뀝니다.

    지어낼 수 없는 것은 지어내지 않습니다. 아무 글자도 못 찾으면 빈
    문자열을 돌려줍니다.
    """
    import re

    sample = "".join(str(t) for t in texts)[:200_000]
    if not sample:
        return "", ""
    counts = [(code, name, len(re.findall(f"[{rng}]", sample)))
              for code, name, rng in _SCRIPTS]
    total = sum(n for _c, _m, n in counts)
    if not total:
        return "", ""

    # 일본어만 예외입니다. 일본어 글에는 한자가 가나보다 많을 수 있어서
    # 그냥 많은 쪽으로 정하면 중국어로 잘못 봅니다. 가나가 제대로 섞여
    # 있으면 일본어입니다.
    kana = dict((c, n) for c, _m, n in counts)["ja"]
    if kana and kana / total >= 0.05:
        return "ja", f"가나 {kana:,}자"

    code, name, n = max(counts, key=lambda x: x[2])
    share = n / total
    if share < _ENOUGH:
        # 비워 두면 플러그인이 **일본어로 칩니다**(기본값이 ja 입니다).
        # 그러니 모르겠다고 손을 놓는 것이 제일 나쁩니다. 제일 많은 것을
        # 고르되, 섞여 있다는 사실을 사람에게 알립니다.
        others = ", ".join(f"{m} {k:,}자" for _c, m, k in
                           sorted(counts, key=lambda x: -x[2])[:3] if k)
        return code, f"여러 말이 섞여 있습니다({others}) — 제일 많은 {name}로 봤습니다"
    return code, f"{name} 글자 {n:,}자 (전체의 {share:.0%})"


def _from_lang(src_lang: str) -> str:
    """원문 언어 코드. ``zh-CN`` 처럼 뒤쪽까지 있는 것은 **그대로** 둡니다.

    예전에는 ``-`` 앞만 잘라 썼습니다. 그러면 중국어가 ``zh`` 가 되어
    플러그인이 짝을 못 찾습니다.
    """
    src = (src_lang or "").strip()
    return "" if src.lower() in ("auto", "all", "") else src


def patch_config(text: str, src_lang: str, dst_lang: str) -> str:
    """이미 있는 설정에서 **세 줄만** 고칩니다.

    ``Endpoint`` 를 비우는 것이 핵심입니다. 그게 켜져 있으면 플러그인이
    글자마다 인터넷에 물어봅니다. 그래서 멈칫하고, 우리 번역표 대신
    엉뚱한 말이 나옵니다 — 실제로 중국어가 영어로 바뀌었습니다.

    나머지 설정은 사용자가 손댔을 수 있으니 건드리지 않습니다.
    """
    want = {"Endpoint": "", "Language": dst_lang,
            "FromLanguage": _from_lang(src_lang)}
    seen: set[str] = set()
    out: list[str] = []
    for line in text.splitlines():
        head = line.split("=", 1)[0].strip()
        if "=" in line and head in want:
            out.append(f"{head}={want[head]}")
            seen.add(head)
        else:
            out.append(line)
    missing = [k for k in want if k not in seen]
    if missing:
        out.append("")
        out += [f"{k}={want[k]}" for k in missing]
    return "\n".join(out) + "\n"


def make_config(src_lang: str, dst_lang: str) -> str:
    """설정. **인터넷 번역기를 끕니다** — 이게 딜레이가 없는 이유입니다.

    플러그인은 없는 항목을 첫 실행 때 알아서 채웁니다. 그래서 우리가
    확실히 아는 것만 적습니다. 모르는 값을 지어내면 게임이 안 뜹니다.
    """
    src = _from_lang(src_lang)
    return (
        "[Service]\n"
        "Endpoint=\n"                       # 비움 = 인터넷 번역 안 함
        "\n"
        "[General]\n"
        f"Language={dst_lang}\n"
        f"FromLanguage={src}\n"
        "\n"
        "[Behaviour]\n"
        "IgnoreWhitespaceInDialogue=True\n"
        "EnableBatching=False\n"
    )


# ---------------------------------------------------------------- 넣기·지우기

def _unpack(zip_path: Path, root: Path, added: list[str]) -> int:
    n = 0
    with zipfile.ZipFile(zip_path) as z:
        for m in z.infolist():
            if m.is_dir():
                continue
            rel = m.filename.replace("\\", "/").lstrip("/")
            if ".." in rel.split("/"):
                continue                    # 압축 파일이 바깥으로 나가려는 것
            dest = root / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            with z.open(m) as fp, dest.open("wb") as out:
                shutil.copyfileobj(fp, out)
            added.append(rel)
            n += 1
    return n


def install(root: Path, bepinex_zip: Path, xunity_zip: Path, proj, lang: str,
            *, src_lang: str = "", with_font: bool = True, ttf: str = "",
            progress=_noop) -> dict:
    """받아 둔 압축 두 개를 게임 폴더에 풀고, 번역표와 한글 글꼴을 깔아 줍니다.

    넣은 파일 목록을 적어 두어 되돌리기가 확실해지게 합니다.

    글꼴은 **같이** 넣습니다. 가로채기는 한글을 뿌려 주지만 게임이 쓰는
    글꼴에 한글 글자가 없으면 화면에는 □□□ 만 남습니다. 두 개를 따로
    두면 사용자가 두 번 손대야 할 뿐 아니라, 한쪽을 되돌릴 때 다른 쪽까지
    사라집니다. 그래서 하나로 묶었습니다.
    """
    root = Path(root)
    # **못 다루는 판이면 손도 대지 않습니다.**
    #
    # BepInEx 5 는 유니티 6000 에서 시작하자마자 죽고, 실패한 주입 때문에
    # 게임까지 검은 화면이 됩니다. 되돌리기 전에는 게임을 못 켭니다.
    # 그러니 "깔아 보고 안 되면 되돌리기" 가 아니라 아예 안 깝니다.
    from .detect import detect

    stop = mono_too_new(detect(root).unity_version) \
        if detect(root).scripting_backend != "IL2CPP" else ""
    if stop:
        raise RuntimeError(stop)
    added: list[str] = []

    # 이미 깔려 있으면 다시 풀지 않습니다. IL2CPP 는 첫 실행 때 몇 분에
    # 걸쳐 준비 작업을 해 두는데, 덮어써서 그걸 날리면 또 몇 분을 기다려야
    # 합니다. 설정과 번역표만 다시 놓으면 됩니다.
    if (root / "BepInEx" / "core").is_dir():
        progress("모드 틀(BepInEx)은 이미 있습니다. 그대로 둡니다.")
    else:
        progress("모드 틀(BepInEx)을 넣습니다…")
        progress(f"  · 파일 {_unpack(Path(bepinex_zip), root, added)}개")

    if list((root / "BepInEx" / "plugins").glob("XUnity*")):
        progress("글자 가로채는 것(XUnity)도 이미 있습니다.")
    else:
        progress("글자 가로채는 것(XUnity)을 넣습니다…")
        progress(f"  · 파일 {_unpack(Path(xunity_zip), root, added)}개")

    text, kept, skipped = make_table(proj, lang)
    if not kept:
        raise RuntimeError("번역된 문장이 없습니다. 먼저 번역을 채우세요.")

    # 원문이 무슨 말인지. 프로젝트가 '자동' 이면 우리는 모릅니다 —
    # 번역표의 원문을 직접 보고 알아냅니다.
    src = _from_lang(src_lang)
    if src:
        progress(f"원문은 {LANG_NAMES.get(src, src)}({src}) 로 두었습니다.")
    else:
        src, why = guess_lang(e.text for e in proj.entries)
        if src:
            progress(f"원문은 {LANG_NAMES.get(src, src)}({src}) 로 보입니다 — {why}.")
            progress("  틀렸으면 [원래대로] 뒤에 원문 언어를 정해 놓고 다시 넣으세요.")
        else:
            progress("※ 원문이 무슨 말인지 알아내지 못했습니다.")
            progress("   원문 언어를 비워 둡니다 — 플러그인이 알아서 하게 둡니다.")

    rel = f"{TRANSLATION}/{lang}/Text/{TABLE}"
    dest = root / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, "utf-8")
    if rel not in added:
        added.append(rel)
    progress(f"번역표 {kept:,}줄을 깔았습니다"
             + (f" (건너뛴 것 {skipped}줄)" if skipped else ""))

    # 설정은 **있으면 고치고** 없으면 새로 씁니다. 예전에는 있으면 그냥
    # 두었는데, 플러그인이 첫 실행 때 자기 설정을 만들어 두므로 우리
    # 설정이 영영 안 먹었습니다 — 인터넷 번역기가 켜진 채로 돌았습니다.
    cfg = root / CONFIG
    cfg.parent.mkdir(parents=True, exist_ok=True)
    if cfg.is_file():
        cfg.write_text(
            patch_config(cfg.read_text("utf-8", errors="replace"),
                         src, lang), "utf-8")
        progress("설정을 고쳤습니다 — 인터넷 번역기를 껐습니다.")
    else:
        cfg.write_text(make_config(src, lang), "utf-8")
        added.append(CONFIG)
        progress("설정을 썼습니다 — 인터넷 번역기는 꺼 두었습니다.")
    progress(f"  · 바꿀 말: {src or '(자동)'} → {lang}")

    (root / ADDED).write_text("\n".join(added), "utf-8")

    # 여기까지는 **글**만 바꿔 놓은 것입니다. 게임이 원래 쓰던 글꼴에 한글이
    # 없으면 화면에는 □□□ 만 뜹니다. 그래서 글꼴까지 같이 넣습니다 —
    # 이 둘을 갈라놓으면 사용자가 두 번 손대야 하고, 한쪽을 되돌릴 때
    # 다른 쪽까지 날아갑니다. 되돌리기는 [원래대로] 하나로 둘 다 걷어냅니다.
    fonts = 0
    if with_font:
        progress("")
        progress("한글 글꼴을 넣습니다 — 이게 없으면 □□□ 로 보입니다.")
        try:
            from .font import fix as font_fix

            frep = font_fix(root, ttf=Path(ttf) if ttf else None,
                            progress=progress)
            fonts = len(frep.patched)
            progress("  " + frep.summary())
        except Exception as exc:                        # noqa: BLE001
            progress(f"  글꼴은 못 넣었습니다: {type(exc).__name__}: {exc}")
            progress("  글자가 □□□ 로 보이면 [한글 폰트 넣기] 를 따로 눌러 보세요.")

    progress("")
    progress("게임을 켜 보세요. 처음 한 번은 준비하느라 오래 걸립니다.")
    progress("되돌리려면 [원래대로]를 누르세요 — 넣은 것만 지웁니다.")
    return {"files": len(added), "lines": kept, "skipped": skipped,
            "fonts": fonts}


def uninstall(root: Path, progress=_noop) -> int:
    """넣었던 것만 지웁니다. 게임 파일은 손대지 않습니다."""
    root = Path(root)
    listing = root / ADDED
    if not listing.is_file():
        progress("넣은 기록이 없습니다.")
        return 0
    n = 0
    dirs: set[Path] = set()
    for rel in listing.read_text("utf-8").splitlines():
        rel = rel.strip()
        if not rel:
            continue
        p = root / rel
        if p.is_file():
            p.unlink()
            n += 1
            dirs.add(p.parent)
    # 빈 폴더는 안쪽부터 치웁니다
    for d in sorted(dirs, key=lambda x: len(x.parts), reverse=True):
        try:
            while d != root and not any(d.iterdir()):
                d.rmdir()
                d = d.parent
        except OSError:
            pass
    listing.unlink()
    progress(f"넣었던 파일 {n}개를 지웠습니다.")
    return n


def installed(root: Path) -> bool:
    return (Path(root) / ADDED).is_file()


# ---------------------------------------------------------------- 파일 찾기

# XUnity 는 이름이 비슷한 것이 11개나 있습니다. 우리가 쓰는 것은
# BepInEx 판 하나뿐이라, 나머지는 이름으로 걸러 냅니다.
_NOT_OURS = ("melonmod", "developer", "ipa", "reipatcher",
             "unityinjector", "resourceredirector")


# 같이 넣어 배포하는 압축이 놓인 자리. 사람에게 받아 오라고 시키지
# 않으려고 둡니다. BepInEx 의 IL2CPP 판은 정식 릴리스가 아니라 빌드
# 서버의 번호별 빌드라, 그 주소는 새 빌드가 나오면 사라집니다. 그래서
# **우리가 실제로 시험해 본 그 빌드**를 그대로 지고 다니는 편이
# 자동으로 받아 오는 것보다 튼튼합니다.
BUNDLED = Path(__file__).resolve().parent / "bundled"


def bundled_for(need) -> tuple[Path | None, Path | None]:
    """이 게임에 맞는 짝이 우리 안에 들어 있으면 그 둘을 돌려줍니다.

    **못 다루는 판이면 아무것도 안 내줍니다.** 있다고 내줬다가 깔면
    게임이 안 켜집니다 — 사용자는 무엇이 망가뜨렸는지 모릅니다.
    """
    if getattr(need, "blocked", ""):
        return None, None
    if not BUNDLED.is_dir():
        return None, None
    bep, xu, _notes = find_zips(BUNDLED, need)
    return bep, xu


def _zips(folder: Path) -> list[Path]:
    if folder.is_file():
        return [folder] if folder.suffix.lower() == ".zip" else []
    if not folder.is_dir():
        return []
    return sorted(p for p in folder.glob("*.zip") if p.is_file())


def find_zips(where: Path, need: Need) -> tuple[Path | None, Path | None, list[str]]:
    """받아 둔 폴더에서 필요한 압축 둘을 골라냅니다.

    사람에게 파일 경로를 타이핑하게 하면 안 됩니다. 실제로 폴더 경로를
    넣어 '파일을 찾지 못했습니다' 만 보게 됐습니다. **폴더를 주면 우리가
    찾습니다.**

    잘못된 판을 받아 왔을 때도 그냥 '없다' 고 하지 않고 **무엇이 잘못
    됐는지** 말해 줍니다 — IL2CPP 게임에 Mono 판을 넣으면 아무 일도
    안 일어나는데, 그 이유를 모르면 영영 헤맵니다.
    """
    want_il2cpp = need.backend == "IL2CPP"
    bep = xu = None
    notes: list[str] = []
    wrong_bep = wrong_xu = None
    mismatched: list[Path] = []

    for f in _zips(Path(where)):
        low = f.name.lower()
        is_xu = "xunity" in low
        is_bep = "bepinex" in low and not is_xu

        if is_xu:
            if any(w in low for w in _NOT_OURS):
                continue
            if ("il2cpp" in low) == want_il2cpp:
                xu = xu or f
            else:
                wrong_xu = wrong_xu or f
        elif is_bep:
            if ("il2cpp" in low) != want_il2cpp:
                wrong_bep = wrong_bep or f
                continue
            got = _bits_in(low)
            if got == need.bits:
                bep = f          # 비트까지 맞는 것이 있으면 그것을 씁니다
            elif got == 0:
                bep = bep or f   # 이름에 안 적혀 있으면 없는 것보다는 낫습니다
            else:
                mismatched.append(f)

    if bep is None and mismatched:
        # 비트가 맞는 것이 하나도 없습니다. 그냥 '없다' 고 하면 사용자는
        # 폴더에 파일이 뻔히 보이는데 왜 안 되는지 알 길이 없습니다.
        notes.append(
            f"{mismatched[0].name} 는 {_bits_in(mismatched[0].name.lower())}비트 "
            f"판인데 이 게임은 {need.bits}비트입니다. "
            f"win_x{'64' if need.bits == 64 else '86'} 판을 받으세요.")
    if bep is None or xu is None:
        notes = _why_not(need, bep, xu, wrong_bep, wrong_xu) + notes
    return bep, xu, notes


def _bits_in(low: str) -> int:
    """파일 이름이 말하는 비트. 모르면 0.

    **32비트는 이름에 ``x86`` 이라고 적힙니다.** ``x32`` 를 찾으면 영영 못
    맞춥니다. 예전에는 ``f"x{need.bits}"`` 로 찾아서, 32비트 게임에
    64비트 BepInEx 를 골라 줬습니다 — 깔려도 게임이 그냥 안 켜집니다.
    """
    flat = low.replace("-", "").replace("_", "").replace(".", "")
    if any(w in flat for w in ("x64", "amd64", "win64", "x8664")):
        return 64
    if any(w in flat for w in ("x86", "win32", "i386")):
        return 32
    return 0


def _why_not(need: Need, bep, xu, wrong_bep, wrong_xu) -> list[str]:
    """무엇이 어긋났고 무엇을 받아야 하는지 **한눈에** 보이게.

    한 줄로 이어 붙이면 아무도 안 읽습니다. 실제로 '이 게임은 Mono
    입니다' 라는 제일 중요한 말이 글 더미에 묻혀 안 보였습니다.
    """
    kind = need.backend or "알 수 없음"
    out = [f"이 게임은 {kind} 입니다."]

    if wrong_bep is not None or wrong_xu is not None:
        got = [f.name for f in (wrong_bep, wrong_xu) if f is not None]
        other = "Mono" if need.backend == "IL2CPP" else "IL2CPP"
        out.append(f"받아 두신 것은 {other} 용입니다:")
        out += ["    " + g for g in got]

    want_il2cpp = need.backend == "IL2CPP"
    out.append("")
    out.append(f"이 게임에 필요한 것은 이 둘입니다 ({kind} · {need.bits}비트).")
    out.append("")
    if want_il2cpp:
        out.append(f"1) 이름에 [Unity.IL2CPP] 와 [win-x{need.bits}] 가 든 것")
        out.append(f"   {BEPINEX_IL2CPP}")
        out.append("")
        out.append("2) 이름에 [BepInEx-IL2CPP] 가 든 것")
    else:
        out.append(f"1) 이름에 [Unity.Mono] 와 [win-x{need.bits}] 가 든 것")
        out.append(f"   {BEPINEX_MONO}")
        out.append("")
        out.append("2) 이름에 [BepInEx] 가 들고 [IL2CPP] 는 없는 것")
    out.append(f"   {XUNITY_RELEASES}")
    if bep is not None or xu is not None:
        have = bep if bep is not None else xu
        out.append("")
        out.append(f"(하나는 맞습니다: {have.name})")
    return out


def guess_folders() -> list[Path]:
    """대개 여기 받습니다. 사람이 경로를 칠 일을 줄입니다."""
    home = Path.home()
    out = [home / "Downloads", home / "다운로드", home / "Desktop",
           home / "바탕 화면"]
    return [p for p in out if p.is_dir()]
